--- # create config for user
apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
data:
  MONGO: "true"
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"

--- # Create a Deployment for user
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    component: user
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: user
      tier: backend
  template:
    metadata:
      labels:
        project: roboshop
        component: user
        tier: backend
    spec:
      containers:
      - name: user
        image: joindevops/user:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: user
        ports:
        - name: liveness-port
          containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15

--- # Create a Service for user
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    component: user
    tier: backend
spec:
  selector:
    project: roboshop
    component: user
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

--- # Create a HorizontalPodAutoscaler for user
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    component: user
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 5
